### ISSUE TITLE
Problem with Anki IPA

### ISSUE THREAD

**Issue by RaZZario** [m-rtin/anki-ipa#10]
Hello,
Unfortunately, your application does not work for me.
I get an error:

**For Anki 2.1.15**
When loading 'Anki IPA':
Traceback (most recent call last):
```
File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons __import__(dir)
File "/home/user_name/.local/share/Anki2/addons21/799647424/__init__.py", line 10, in <module>
from .import main
File "/home/user_name/.local/share/Anki2/addons21/799647424/main.py", line 18, in <module>
from .import batch_adding
File "/home/user_name/.local/share/Anki2/addons21/799647424/batch_adding", line 15, in <module>
from .typing import List
File "/home/user_name/.local/share/Anki2/addons21/799647424/typing.py", line 1357, in <module>
class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
File "/home/user_name/.local/share/Anki2/addons21/799647424/typing.py", line 1005, in __new__
self ._abc_registry = extra._abc_registry
AttributeError:type object 'Callable' has no attribute' _abc_registry'
```

**For Anki 2.1.19**
When loading 'Anki IPA':
Traceback (most recent call last):
```
File "aqt/addons.py", line 97, in loadAddons
File "/home/user_name/.local/share/Anki2/addons21/799647424/__init__.py", line 10, in <module>
from . import main
File "/home/user_name/.local/share/Anki2/addons21/799647424/main.py", line 18, in <module>
from . import batch_adding
File "/home/user_name/.local/share/Anki2/addons21/799647424/batch_adding.py", line 15, in <module>
from .typing import List
File "/home/user_name/.local/share/Anki2/addons21/799647424/typing.py", line 1357, in <module>
class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
File "/home/user_name/.local/share/Anki2/addons21/799647424/typing.py", line 1005, in __new__
self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

**I used:**
Linux 5.4.13-3-MANJARO x86_64 GNU/Linux
Anki Version 2.1.15 (442df9d6) Python 3.8.1 Qt 5.14.0 PyQt 5.14.1
Anki Version 2.1.19 (3c8690ae) Python 3.8.1 Qt 5.14.0 PyQt 5.13.2 

P.S. I'm using Version 2.1.15 now

**Comment by RaZZario** [comment]
`Try running "pip uninstall typing" in your terminal, maybe this will help. If yes, please update your Issue in Github.`

So as you advised, I tried to run "pip uninstall typing", but it didn't help.

**Comment by m-rtin** [comment]
It seems that the typing module is now integrated into Anki. I updated the sourcecode, now everything should work fine. Please update the addon within Anki and report if your issue is resolved.

**Comment by RaZZario** [comment]
> It seems that the typing module is now integrated into Anki. I updated the sourcecode, now everything should work fine. Please update the addon within Anki and report if your issue is resolved.

Unfortunately, it doesn't work.
I got error:
`Error downloading 799647424: invalid code, or add-on not available for your version of Anki.`

Now I use the Version 2.1.15 (442df9d6)

**Comment by m-rtin** [comment]
Thanks for your feedback. Could you please try it again, I changed the allowed Anki version in Anki Web.

**Comment by RaZZario** [comment]
> Thanks for your feedback. Could you please try it again, I changed the allowed Anki version in Anki Web.

I checked it again. It seems to look good.
Thanks a lot.

**Comment by RaZZario** [comment]
I checked it again. It seems to look good.
Thanks a lot.
P.S I updated the comment on the GitHub.
