### ISSUE TITLE
IPA add-on not working in anki

### ISSUE THREAD

**Issue by laural97** [m-rtin/anki-ipa#22]
When I click on the notes to add a IPA pronunciation, this error message comes up. I deleted and reinstalled the addon and the problem still persists. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-14 23:02:04

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-2>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Laura Erickson\AppData\Roaming\Anki2\addons21\799647424\main.py", line 183, in on_bridge_cmd
    _old(editor, command)
  File "aqt\editor.py", line 416, in onBridgeCmd
  File "C:\Users\Laura Erickson\AppData\Roaming\Anki2\addons21\799647424\main.py", line 64, in paste_ipa
    ipa = parse_ipa_transcription.transcript(words=words, language=lang_alias)
  File "C:\Users\Laura Erickson\AppData\Roaming\Anki2\addons21\799647424\parse_ipa_transcription.py", line 81, in transcript
    transcription_method = transcription_methods[language]
KeyError: ''

**Comment by kazemihabib** [comment]
The language by default has been set to "eng_a" but there is no such language change it to eng from the menu.

**Comment by m-rtin** [comment]
The problem should be solved now.
