### ISSUE TITLE
Crashing on 'ger' IPA

### ISSUE THREAD

**Issue by mrderiuzz** [m-rtin/anki-ipa#24]
as in the title. Logs below. Let me know if you need anything else?

```
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-16 20:27:12

--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1250.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u02c8' in position 82: character maps to <undefined>
Call stack:
  File "runanki", line 4, in <module>
  File "aqt\__init__.py", line 400, in run
  File "aqt\__init__.py", line 570, in _run
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Users\Darek\Documents\Anki\decorator.pyc:decorator-gen-20>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Darek\AppData\Roaming\Anki2\addons21\799647424\main.py", line 183, in on_bridge_cmd
    _old(editor, command)
  File "<C:\Users\Darek\Documents\Anki\decorator.pyc:decorator-gen-18>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Darek\AppData\Roaming\Anki2\addons21\516643804\main.py", line 135, in onBridge
    return _old(self, str)
  File "aqt\editor.py", line 418, in onBridgeCmd
  File "C:\Users\Darek\AppData\Roaming\Anki2\addons21\799647424\main.py", line 68, in paste_ipa
    logging.debug(f"IPA transcription string: {ipa}")
  File "logging\__init__.py", line 2077, in debug
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'IPA transcription string: ˈmɪtˌlaɪ̯dn̩'
Arguments: ()
```

**Comment by m-rtin** [comment]
Thanks for your feedback! Could you update to the newest version of the addon and try again? Could you send a screenshot? On my machine it looks like this:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/46455311/182034663-7074b89b-9421-4f7d-a589-bc2f31179aed.png">

**Comment by mrderiuzz** [comment]
Thanks for the reply. Nevermind, I switched to another add on. Have a good one!
