### ISSUE TITLE
Error generated every time IPA is generated

### ISSUE THREAD

**Issue by anundesirable** [m-rtin/anki-ipa#34]
Each time I generate an IPA transcription, an error is generated (but the IPA is generated successfully anyways)

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
> Debug info:
> Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
> Platform: Mac 10.16
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2021-12-13 14:36:01
> Add-ons possibly involved: ⁨Anki IPA⁩
> 
> --- Logging error ---
> Traceback (most recent call last):
>   File "logging/__init__.py", line 1084, in emit
> UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 29: ordinal not in range(128)
> Call stack:
>   File "runankimac", line 12, in <module>
>   File "aqt/__init__.py", line 437, in run
>   File "aqt/__init__.py", line 618, in _run
>   File "aqt/webview.py", line 41, in cmd
>   File "aqt/webview.py", line 142, in _onCmd
>   File "aqt/webview.py", line 595, in _onBridgeCmd
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 86, in repl
>   File "/Users/tysonwang/Library/Application Support/Anki2/addons21/799647424/main.py", line 183, in on_bridge_cmd
>     _old(editor, command)
>   File "aqt/editor.py", line 438, in onBridgeCmd
>   File "/Users/tysonwang/Library/Application Support/Anki2/addons21/799647424/main.py", line 51, in paste_ipa
>     logging.debug(f"Field text: {field_text}")
>   File "logging/__init__.py", line 2080, in debug
>   File "logging/__init__.py", line 1422, in debug
>   File "logging/__init__.py", line 1577, in _log
>   File "logging/__init__.py", line 1587, in handle
>   File "logging/__init__.py", line 1649, in callHandlers
>   File "logging/__init__.py", line 950, in handle
>   File "logging/__init__.py", line 1183, in emit
>   File "logging/__init__.py", line 1089, in emit
> Message: 'Field text: das Maß, Maße'
> Arguments: ()
> --- Logging error ---
> Traceback (most recent call last):
>   File "logging/__init__.py", line 1084, in emit
> UnicodeEncodeError: 'ascii' codec can't encode character '\xdf' in position 33: ordinal not in range(128)
> Call stack:
>   File "runankimac", line 12, in <module>
>   File "aqt/__init__.py", line 437, in run
>   File "aqt/__init__.py", line 618, in _run
>   File "aqt/webview.py", line 41, in cmd
>   File "aqt/webview.py", line 142, in _onCmd
>   File "aqt/webview.py", line 595, in _onBridgeCmd
>   File "decorator.py", line 232, in fun
>   File "anki/hooks.py", line 89, in decorator_wrapper
>   File "anki/hooks.py", line 86, in repl
>   File "/Users/tysonwang/Library/Application Support/Anki2/addons21/799647424/main.py", line 183, in on_bridge_cmd
>     _old(editor, command)
>   File "aqt/editor.py", line 438, in onBridgeCmd
>   File "/Users/tysonwang/Library/Application Support/Anki2/addons21/799647424/main.py", line 60, in paste_ipa
>     logging.debug(f"Word list: {words}")
>   File "logging/__init__.py", line 2080, in debug
>   File "logging/__init__.py", line 1422, in debug
>   File "logging/__init__.py", line 1577, in _log
>   File "logging/__init__.py", line 1587, in handle
>   File "logging/__init__.py", line 1649, in callHandlers
>   File "logging/__init__.py", line 950, in handle
>   File "logging/__init__.py", line 1183, in emit
>   File "logging/__init__.py", line 1089, in emit
> Message: "Word list: ['das', 'maß,', 'maße']"
> Arguments: ()

**Comment by m-rtin** [comment]
Thanks for your feedback! Could you update to the newest version of the addon and try again? Could you send a screenshot?
