### ISSUE TITLE
Error when selecting 'eng' variant

### ISSUE THREAD

**Issue by engilas** [m-rtin/anki-ipa#42]
**Describe the bug**
When selecting 'eng' or hitting 'play' button with 'eng' selected in add note window, the error appears.

`
Error
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-04 09:35:06

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\rydaev\AppData\Roaming\Anki2\addons21\799647424\__init__.py", line 182, in on_bridge_cmd
    on_ipa_language_select(editor, lang)
  File "C:\Users\rydaev\AppData\Roaming\Anki2\addons21\799647424\__init__.py", line 155, in on_ipa_language_select
    alias = consts.LANGUAGES_MAP[lang]
KeyError: 'eng'

`

**Comment by engilas** [comment]
After restart 'eng' variant has dissapeared.

**Comment by m-rtin** [comment]
I removed the "eng" variant. You now have to choose between American English ("eng_a") and British English ("eng_b").
