### ISSUE TITLE
Error/bug - Extension not working

### ISSUE THREAD

**Issue by Marcosffn** [m-rtin/anki-ipa#53]
Using the extension to get IPA from English only words. It used to work in past few weeks and now don't. I've just tried to reinstall the extension and nothing changed.
Actually, if I use the option to add IPA in multiples cards it works, but the icon on the add cards bar or the editor in the sidebar doesn't work and I get the error below.

Informações de Depuração:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-21 12:16:39
Extensões possivelmente envolvidas: ⁨Anki IPA⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/marcos/.local/share/Anki2/addons21/799647424/__init__.py", line 178, in on_bridge_cmd
    _old(editor, command)
  File "aqt.editor", line 467, in onBridgeCmd
  File "/home/marcos/.local/share/Anki2/addons21/799647424/__init__.py", line 60, in paste_ipa
    ipa = parse_ipa_transcription.transcript(words=words, language=lang_alias)
  File "/home/marcos/.local/share/Anki2/addons21/799647424/parse_ipa_transcription.py", line 159, in transcript
    transcription_method = transcription_methods[language]
KeyError: ''

**Comment by Marcosffn** [comment]
I changed from "eng" to "eng_a" and now works, in the add cards panel.

**Comment by m-rtin** [comment]
The `eng` option should not be available anymore, you have to choose between American English `eng_a` and British English `eng_b`.
